### ISSUE TITLE
NRRD space setting from imported NRRD files not preserved

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/Seg3D#1]
The NRRD space setting from imported NRRD files is not preserved when the file is exported to NRRD. Space directions is also not preserved from the imported NRRD. Basically NRRD0004 settings are overridden with NRRD0001 settings. Migrated from GForge [issue tracker](https://gforge.sci.utah.edu/gf/project/seg3d2/tracker/?action=TrackerItemEdit&tracker_item_id=824&start=0).

**Comment by aylakhan** [comment]
More testing required here...

**Comment by gduffley** [comment]
Even if Seg3D doesn't use the space information for displaying a .nrrd, it would be great if Seg3D conserved the header when saving. It would also be great if a mask exported uses the same header information than the data it originally derived from.

**Comment by aylakhan** [comment]
Investigate converting original NRRD header to string, and propagate through layer group as metadata.
