### ISSUE TITLE
Quitting from python sometimes segfaults

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/Seg3D#104]
Quitting Seg3D from the python console (using quit()) sometimes crashes the application with a segfault (tested on OS X).

**Comment by thoth291** [comment]
May be in your case it is different - but I solved this issues by registering `atexit` function in python and did a proper cleanup of my memory allocations and opened file descriptors.

**Comment by aylakhan** [comment]
Looks like it's a multithreading Qt problem.
