### ISSUE TITLE
Otsu threshold filter crashes on Windows

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#109]
The Otsu threshold filter has been reported to crash on Windows 7 64-bit with a >3GB dataset.

**Comment by aylakhan** [comment]
Re-check with upgraded ITK in newest builds.

**Comment by allywarner** [comment]
Check on current Windows OS. Likely not an issue anymore.

**Comment by allywarner** [comment]
Tested with 9.6GB TIFF stack and crashed on read. Libtiff64 and int styling might be the problem. Testing if new ITK 5.1.0 will help.

**Comment by allywarner** [comment]
Fixed with ITK 5.2.
