### ISSUE TITLE
Add a fuzzy select/magic wand tool

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#11]
Add a fuzzy select/magic wand tool that selects pixels in a contiguous area based on pixel values. Migrated from GForge [issue tracker](https://gforge.sci.utah.edu/gf/project/seg3d2/tracker/?action=TrackerItemEdit&tracker_item_id=876&start=0).

**Comment by allywarner** [comment]
This functionality exists using the confidence connected filter.
