### ISSUE TITLE
abort on startup in QOpenGLContext::make_current

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/Seg3D#118]
Qt5 requires some more care in how GLContext make_current is called in a threaded environment.  Follow the Qt4-Qt5 migration recommendations for handling this.

**Comment by aylakhan** [comment]
Specifically: http://doc.qt.io/qt-5/qopenglcontext.html#makeCurrent.

**Comment by krismz** [comment]
Unfortunately, [moveToThread] (http://doc.qt.io/qt-5/qobject.html#moveToThread) will not work when a QOpenGLContext is created on one thread and used on another because the creation happens on boost threads, but moveToThread needs a QThread pointer.  Therefore, ensure that QOpenGLContexts are created on the same thread on which they will be used and that QOpenGLContexts are only used on their intended thread.
