### ISSUE TITLE
update build instructions for Qt5

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/Seg3D#120]
Update the developer build instructions on the [Seg3D webpage] (http://www.sci.utah.edu/software/seg3d.html) to include how to build Qt5 appropriately.  This shouldn't be done until the Qt5 changes have been merged and released.  

Mac 

- update version info to Qt5 

Windows 

- update version info to Qt5
- refer to [Qt docs] (http://doc.qt.io/qt-5/windows-requirements.html#building-from-source) on requirements for building from source
- change configure command and parameters to

 `configure -platform win32-msvc2013 -no-gif -qt-libpng -qt-zlib -qt-libjpeg -no-openssl -skip qtwebengine -skip qtwebkit -D _BIND_TO_CURRENT_VCLIBS_VERSION=1 -debug-and-release -opensource -opengl desktop`

- If Qt5 is installed to custom location, set CMAKE_PREFIX_PATH in CMake to include the Qt5 install prefix by setting it to C:/path/to/qt5/ where qt5 contains a bin directory that contains qmake
- In CMake, turn off DO_ZLIB_MANGLE

Linux

- update version info to Qt5
- change configure command and parameters to 

`./configure -qt-xcb -qt-zlib -nomake examples -nomake tests -skip qtwayland -skip qtwebengine -skip qtwebkit -opengl desktop`

where Qt5 is now built dynamically to better match typical user configurations with system installs of Qt5.

_more coming here, as it gets figured out_

**Comment by aylakhan** [comment]
Actually, we're building out a new doc site at https://github.com/SCIInstitute/seg3d.pages - all build instructions will migrated there.

**Comment by aylakhan** [comment]
Updated here: http://sciinstitute.github.io/seg3d.pages/build.html.
