### ISSUE TITLE
undefined references to symbols when linking Qt5 on Linux

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/Seg3D#123]
See error messages like:
`libQt5Widgets.a(qgtkstyle_p.o): undefined reference to symbol 'XSetErrorHandler' /lib64/libX11.so.6: error adding symbols: DSO missing from command line`

This is because Seg3D links in a static build of Qt on linux, and needs to then add libraries Qt is dependent on to its TARGET_LINK_LIBRARIES.

**Comment by krismz** [comment]
Workaround by just linking Qt dynamically on Linux.  Leaving open as low priority.

**Comment by aylakhan** [comment]
Works - we'll have to be careful about documenting this for Linux builds.

**Comment by krismz** [comment]
Agreed.  A comment about linking dynamically has been added to #120 that captures build changes for Qt5.

**Comment by aylakhan** [comment]
Perfect, thank you

**Comment by aylakhan** [comment]
Looks like we're OK with documentation.
