### ISSUE TITLE
FreeType font error on linux

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/Seg3D#124]
When Seg3D with Qt5 is started on linux, the following error message appears several times:
`ERROR: Failed to create a new face from font file`

Probably not worth addressing until after #51

**Comment by krismz** [comment]
This is probably because on cibc-test1 (CentOS), FreeSerif.ttf is in /usr/share/fonts/gnu-free/

**Comment by aylakhan** [comment]
Should be checked on Fedora too (machine is dual-boot).
