### ISSUE TITLE
ITK doesn't compile with GCC 5.1

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/Seg3D#125]
According to [this ITK issue] (https://issues.itk.org/jira/browse/ITK-3361), VNL compiler checks need to be updated to handle GCC 5.1 in order to get past the "Dunno about this gcc" compile error that appears.  This was noticed on cibc-test4, a Ubuntu 15.10 platform.  Can either avoid gcc 5 for now on this machine, or can upgrade ITK version which might affect #35, or can apply the patch as found [here] (http://review.source.kitware.com/#/c/19724/) to ITK as part of the build process.

**Comment by aylakhan** [comment]
ITK repo has been patched. ITK upgrade coming in the near future.
