### ISSUE TITLE
exposing the group of a layer

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Seg3D#126]
For the python console, it would be nice to be able to access the group info for a given layer.  The data is saved as stateids for the groups, but, there is no way to know what group a given layer is assigned.

**Comment by jessdtate** [comment]
are the provedance_id or generation information related to these?

**Comment by jessdtate** [comment]
looks like the generation and provendance_id or just the order that the layers are created, which is similar to the groups, but if there is more that one layer per group, then it doesn't correlate.

**Comment by aylakhan** [comment]
Will create a query method ( **getlayergroup(layer=layerid)** ) instead of adding a new state, which will be safer for keeping layer state consistent.
