### ISSUE TITLE
speedline path smoothness and seed ordering

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/Seg3D#134]
The speedline tool computed path seems less smooth than it should be (at the very least when compared to a Matlab LiveWire implementation for the same seed points and image).  Additionally, sometimes the seed points get out of order on the path.  It's not clear whether this has something to do with the implementation of LiveWire itself or if it has more to do with the way the path is either constructed or managed in Seg3D.

I tested with these images:

![star_60](https://cloud.githubusercontent.com/assets/1117600/13299057/b01a523e-daf6-11e5-9b58-62a63fdec709.png)
![house_crop](https://cloud.githubusercontent.com/assets/1117600/13299076/c4419f1a-daf6-11e5-8a8a-21de84de4089.png)
![brain_labels](https://cloud.githubusercontent.com/assets/1117600/13299110/e2f532b4-daf6-11e5-8b63-bd450c3fdc65.png)

**Comment by aylakhan** [comment]
It may also be worth reviewing the filters used in the livewire implementation to see if use can be improved, or a better option is available (i.e. gradient magnitude).

**Comment by aylakhan** [comment]
Also, the Seg3D Path class may need to either be improved or replaced.
