### ISSUE TITLE
GUI window gets longer when saving 

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/Seg3D#153]
I am using a retina display macbook pro with OS X 10.11.5. When I move the pane out of view that shows the axial, coronal, and sagittal views, do some work and then save the gui window gets longer. If I do more work and then save again, it gets even longer.

**Comment by aylakhan** [comment]
Still a problem with Qt5 version.

**Comment by allywarner** [comment]
Don't see this issue on OSX 10.14.6 with Qt. 5.14. Will test on Windows.

**Comment by allywarner** [comment]
No longer a bug on Windows using Qt 5.14.
