### ISSUE TITLE
Checker box in top left corner

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/Seg3D#154]
![screen shot 2016-06-09 at 12 11 51 pm](https://cloud.githubusercontent.com/assets/5941547/15940989/983d55e2-2e3b-11e6-8f66-1a999a341bda.png)

**Comment by aylakhan** [comment]
Looks like it disappears after some time...

**Comment by aylakhan** [comment]
Needs testing on Linux

**Comment by krismz** [comment]
This doesn't exist with Qt 5.5, does with Qt 5.6.  The checkerboard is not visible until after the splash screen goes away.  Checkerboard is even present if Seg3D has been started with all dock windows closed.  It's behind the viewer panels in that case, but the edges of it can be seen.

**Comment by aylakhan** [comment]
Also, checkerboard never shows up in server mode, probably because the splash screen doesn't get rendered.

**Comment by aylakhan** [comment]
Passing bug off to Collin for further investigation.

**Comment by aylakhan** [comment]
@collint8 the updated SplashScreen is in the qt5_fixes branch, so you should work there.

**Comment by collint8** [comment]
Appears to be corrected in Qt5.9.
