### ISSUE TITLE
UI issues 

### ISSUE THREAD

**Issue by wgood** [SCIInstitute/Seg3D#156]
- [x] Black MRI and Black background does not help with contrast issues. Should have complete control over this if we do not. 
- [x] Settings buttons should have a larger typeset. (ISO button etc)
  <img width="291" alt="icons" src="https://cloud.githubusercontent.com/assets/1399377/15943484/880da81a-2e46-11e6-8649-3b757c26c2fb.png">
- [x] Little contrast between a selected button and a non-selected button. (ISO on versus off).

**Comment by aylakhan** [comment]
Could ramp the gray level up or down...

**Comment by krismz** [comment]
Is it enough control to change the background color in Preferences->View->Background color ?

**Comment by wgood** [comment]
The people here seem to think that it isn't good enough to change just the background. We would like to the color of the whole program to be modifiable in the same way.
