### ISSUE TITLE
Renderer window scaling

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#157]
The rendering area does not scale with the slice and volume views on laptops.

<img width="729" alt="render_win" src="https://cloud.githubusercontent.com/assets/1399377/15942426/88825142-2e41-11e6-857d-c5d601167947.png">

**Comment by aylakhan** [comment]
Turning off NSHighResolutionCapable MacOSXBundleInfo.plist.in works for now...

**Comment by allywarner** [comment]
Could turn on NSHighResolutionCapable in MacOSXBundleInfo.plist.in without having 1/4 rendering area. Fixed underlying problem.
