### ISSUE TITLE
Measurement of objects' sizes and shapes with a data file output

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#16]
From Sidnei Paciornik:

Measurement of objects' sizes and shapes with a data file output (I am aware of the connected component size function but I cannot figure how to extract the size measurements - all I could do was segment the component size image based on size/greyscale).

Migrated from GForge [issue tracker](https://gforge.sci.utah.edu/gf/project/seg3d2/tracker/?action=TrackerItemEdit&tracker_item_id=863&start=0).

**Comment by allywarner** [comment]
In the info tab of the layer menu, users can calculate the volume of a mask layer. 

The value of the connected component by size regions are the number of pixels. The default option is to use a logarithmic scale. This can be disabled to provide the number of pixels in each region. The value can be multiplied by the volume of each pixel (Arithmetic filter) to get the true volume or absolute volume.
