### ISSUE TITLE
export layer not saving files in python console

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Seg3D#163]
When exportlayer is called from the python console, it will return a value of true, but it will not save any files.  This occurs in version 2.3.1 or newer, but exportlayer works in 2.3.0.  Exporting layers works fine when called through the gui.

Additionally, exportsegmentation will write out files in the newer versions.

To reproduce this bug:

1. load in a dataset as a data layer
2. open the python console
3. export the layer with the function:
`exportlayer(layer='layer_0',file_path='[path]',exporter='[NRRD Exporter]',extension='.nrrd')`
4. Seg3D log will state that file was saved, but no file exists.

the results are the same when tried with different exporters (matlab and ITK Data).

**Comment by aylakhan** [comment]
Closed in 6a79e08fe0268529be875c34836aa44c5775c46c.
