### ISSUE TITLE
Curvature AnisioDiff Filter Mutilates/evicerates input data

### ISSUE THREAD

**Issue by wgood** [SCIInstitute/Seg3D#168]
Using the heart geometry used in IBBM (../IBBM/2016/Image_Processing/Lab2/DICOM/)  and running the Curvature AnisioDiff Filter returns a really corrupted output. Degree of corruption seems to vary, but none have been usable. Does not extend to every geometry. 

![image](https://cloud.githubusercontent.com/assets/12956759/16784573/90fa6836-4846-11e6-8ad4-7b0a09ab4502.png)

**Comment by aylakhan** [comment]
Example in Checker.nrrd (in scratch).
