### ISSUE TITLE
Exporting many segmentations as a single nrrd does not work with overlapping segmentations

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/Seg3D#169]
Paint several overlapping circles on a slice and export as a single segmentation. Then load the file into Seg3D and you will lose the portion of your segmentation that is overlapping with another segmentation.

**Comment by jessdtate** [comment]
This is a limitation of most file formats. Most only allow a single value for each pixel.  If you want to preserve the overlap, you will need to use the multiple files option.

**Comment by allywarner** [comment]
File format limitation. Will not implement.
