### ISSUE TITLE
Drawing tool that interpolates a line between seed points

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#17]
This is a request from Sila Kurugol (Harvard) for a drawing tool that interpolates a line (in Fourier domain) between seed points. Sila will supply Matlab code for interpolation. Migrated from GForge [issue tracker](https://gforge.sci.utah.edu/gf/project/seg3d2/tracker/?action=TrackerItemEdit&tracker_item_id=851&start=0).

Matlab code doesn't work - need to re-implement...

**Comment by allywarner** [comment]
Example code not working. Will not implement.
