### ISSUE TITLE
NIfTI file export failing for masks

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#172]
NIfTI and compressed NIfTI file export is failing for mask layers. See also sample files from Ally.

**Comment by aylakhan** [comment]
Fixed in fbde0cca25a86253bdf0d85eb389d8a39749fe30.

**Comment by jessdtate** [comment]
looks like the exporter is failing again. no files are being generated for segmentations.  Also, no log message is generated even with data layers.

**Comment by allywarner** [comment]
File types with no log: dicom, bitmap, png, tiff. 
File types with no log and no save: nifti, mha, compressed nifti. 
These are all ITK exporters.
