### ISSUE TITLE
Improve Seg3D Python console

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/Seg3D#175]
- [x] Multiline copy and paste support
- [x] Copy and paste from context menu vs Control/Command - V
- [x] Is command prompt formatting a problem?

**Comment by thoth291** [comment]
I guess it can be solved in ipython console with %paste magic.

**Comment by aylakhan** [comment]
Fixed in 4f75cf82d7bf3ad826eca14e4f2c030d02e52b39. Setting the prompt to another color does screwy things to text when pasting.
