### ISSUE TITLE
Some compilcation on windows10+VS2013+cmake3.6+QT5.7

### ISSUE THREAD

**Issue by coolalexzb** [SCIInstitute/Seg3D#183]
Hello , I come from China and I am a green hand in this field .
I have some question .
When I use cmake3.6 to compile the source code , some errors arise , most of them are unknown command , such as "add_test_dir" ,"core_add_library" and so on . 
What is more , how can I get a .exe ?  I get a .lib sometimes .
When I run a source code , how can I link with QT ? I do not want to link manually each time .
Bother you some time to answer my question. Thank you very much .

**Comment by aylakhan** [comment]
Could you please provide more details? Screenshots and log snippets would be helpful.

**Comment by coolalexzb** [comment]
This some errors in superbuild
<img width="546" alt="image" src="https://cloud.githubusercontent.com/assets/19755247/22275386/4f227c28-e2e7-11e6-980f-e7ea715a0ce9.png">
This is one of unknown command ， "add_test_dir"  is noted by me
<img width="816" alt="image" src="https://cloud.githubusercontent.com/assets/19755247/22275428/aaa03310-e2e7-11e6-88f7-5d9daa181bfd.png">
<img width="300" alt="image" src="https://cloud.githubusercontent.com/assets/19755247/22275434/bb846b9c-e2e7-11e6-9a32-1f29488fc53a.png">
This is some other errors
<img width="783" alt="image" src="https://cloud.githubusercontent.com/assets/19755247/22275469/edcdb2de-e2e7-11e6-8cec-06eab244c1d3.png">
<img width="714" alt="image" src="https://cloud.githubusercontent.com/assets/19755247/22275475/ff9dfea6-e2e7-11e6-98e7-35739cf8edf8.png">

**Comment by aylakhan** [comment]
Looks like you're not configuring the CMake project correctly. We do not support building binaries in the source directory. Also, the source directory should be Superbuild. Build instructions are found on this page: http://sciinstitute.github.io/seg3d.pages/build.html (link can also be found on the README page).

**Comment by coolalexzb** [comment]
@aylakhan

**Comment by aylakhan** [comment]
Redoing the CMake configuration should fix this issue.
