### ISSUE TITLE
Add cubic spline basis to Implicit Model tool

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#187]
Option needs to be added to GUI in Seg3D. Implementation goes in the [Implicit Model library](https://github.com/SCIInstitute/ImplicitFunction).

**Comment by allywarner** [comment]
After speaking with Ross Whitaker, cubic spline kernel doesn't make as much sense because it's similar to the multi-quadratic kernel. It's not the same as cubic interpolation.
