### ISSUE TITLE
some problems about configuraton(WIN10+VS2013+CMAKE3.6.1+QT5.7)

### ISSUE THREAD

**Issue by coolalexzb** [SCIInstitute/Seg3D#195]
Hello, I am a green hand in this field . I have some questions about build the environment .I have been in a suck for a long time . Please spare some time for me to solve the problems . Thank you very much .
The first one is when I compile the Superbuild , the error is as follow: the Chinese means that "the program has exited "

![image](https://cloud.githubusercontent.com/assets/19755247/22405515/ec63396a-e67e-11e6-8ee9-cdc071cf38cb.png)
![image](https://cloud.githubusercontent.com/assets/19755247/22405503/c719f2fc-e67e-11e6-99f0-8e7eff38eb57.png)

The second is when I use cmake3.6.1 to compile Cmakelist , the error messages are "unknown command" or some other errors , is caused by version? The following are some of the problems .

![image](https://cloud.githubusercontent.com/assets/19755247/22405530/24a937ac-e67f-11e6-9b0f-bc22a52656ae.png)

![image](https://cloud.githubusercontent.com/assets/19755247/22405534/3bae19ea-e67f-11e6-99cd-14f1c88cfb27.png)
![image](https://cloud.githubusercontent.com/assets/19755247/22405540/5894f0a6-e67f-11e6-96c8-fe959fe7dad0.png)

![image](https://cloud.githubusercontent.com/assets/19755247/22405490/9bc0c748-e67e-11e6-8826-07b4193d6b6a.png)
![image](https://cloud.githubusercontent.com/assets/19755247/22405522/09d1a90a-e67f-11e6-9ee1-2dfa37d31774.png)

**Comment by aylakhan** [comment]
Suggestions for fixing the build have been sent by email.

**Comment by coolalexzb** [comment]
I am sorry that I did not receive the suggestions .


At 2017-02-10 07:42:19, "Ayla Khan" <notifications@github.com> wrote:


Suggestions for fixing the build have been sent by email.
