### ISSUE TITLE
Build fails due to ImplicitFunction looking for TetgenConfig.cmake

### ISSUE THREAD

**Issue by brocktice** [SCIInstitute/Seg3D#198]
It appears that the setup for making this build in Travis-CI is preventing a normal command-line build with cmake or build.sh, as it's looking for tetgen and associated files, which are not included and not downloaded as part of non-Travis builds.

**Comment by yxqd** [comment]
I wonder if this is somewhat related to the question I posted on Seg3D mailing list here: https://lists.sci.utah.edu/sympa/arc/seg3d/2017-02/msg00000.html?
Any help is appreciated.

**Comment by brocktice** [comment]
It's likely this bug should actually go in the ImplicitFunction project, now that I've looked into it more.

**Comment by brocktice** [comment]
This issue only seems to happen with 2.3.2. The latest version from git built just fine. I suspect incompatibility between changes in the ImplicitFunction build and the old 2.3.2 Seg3D build.

An older ImplicitFunction checkout from the same time frame would probably fix it.
