### ISSUE TITLE
My Seg3D only show console window and does not display GUI

### ISSUE THREAD

**Issue by XYZ916829** [SCIInstitute/Seg3D#209]
After I compiled Seg3D source code, only a console is shown, without the GUI.
The program was finally repeating in a while loop like this:
```
while(seg3d_forever)
  {
    // do nothing, check every second for a termination signal
    boost::this_thread::sleep(boost::posix_time::milliseconds(1000));
  }
```

I noticed that there are no slots connected with this signal:
```
 Core::Application::Instance()->application_start_signal_();
```

Is this the reason why I could not start the program?
Or, do I need to pass any parameters to the main function?

**Comment by aylakhan** [comment]
Can you please report OS and version, and Qt version you compiled against?

**Comment by XYZ916829** [comment]
@aylakhan 
I'm using Windows 10 64bit, VS2013, and Qt 5.8.0 x64

**Comment by aylakhan** [comment]
Please use Qt 5.5 as shown in the [build instructions](http://sciinstitute.github.io/seg3d.pages/build.html#seg3d-24-and-newer). We're still working our way through Qt 5 bugs.

**Comment by XYZ916829** [comment]
@aylakhan thanks for replaying!
I've changed Qt 5.5 to build and compile, but it still shows a console only.
![image](https://cloud.githubusercontent.com/assets/14884056/24827437/2f24c20e-1c7c-11e7-85df-371515325dbe.png)

**Comment by aylakhan** [comment]
What happens if you try to start the Seg3D application from File Explorer?

**Comment by XYZ916829** [comment]
The same to run from IDE.

**Comment by aylakhan** [comment]
Can you try building in Debug mode with the console enabled?
