### ISSUE TITLE
problems with dicom exporter/importer.  

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Seg3D#216]
Seg3D with the ITK update has a hard time loading the dicoms it saves out.  I suspect this is more a problem with the exporter, because other software (osirix) also has a problem with the dicoms that Seg3D saves out.  However, the exporter seems the same since 2.3 (same problems in osirix).  

The problem is that the spacing information isn't properly saved or loaded, even in other software, though the metadata there.  It could be in the wrong place.  

This seems to only be a problem when converting files from nrrd format to dicom, as files loaded as dicoms export fine. 

to reproduce the error, load a nrrd file from the example data, save it as a dicom, then try to load it again.

**Comment by jessdtate** [comment]
Though there may be a problem with the exporter, the same data imports fine in 2.3. Therefore the importer is different between versions.

**Comment by jessdtate** [comment]
I get an error trying to build:
CMake Error: File /Users/jess/software/SCIRun_mine/src/CMake/Modules/CPack.Distribution.dist.in does not exist.
CMake Error at CMakeLists.txt:976 (CONFIGURE_FILE):
  configure_file Problem configuring file

**Comment by aylakhan** [comment]
The ITK library was changed between 2.3 and 2.4.

**Comment by aylakhan** [comment]
So far:
- debugging into itkGDCMImageIO.cxx in the ITK library shows that origin. spacing and per-slice origin are being read correctly in the Write function
- opening the dicom files in ITK-Snap shows the origin set (incorrectly) to [0,0,0] and the spacing z component set to 1

**Comment by aylakhan** [comment]
The ITK library branch with the Numira/CARMA custom code disabled is [gdcm_fix](https://github.com/CIBC-Internal/itk/compare/gdcm_fix).

**Comment by aylakhan** [comment]
Using pydicom to view the dicom headers, for example:

>>> import dicom
>>> plan = dicom.read_file("Seg3D/Seg3DData/Heart_DataSet/Angio-00.dcm")
>>> print(plan)
>>> (0008, 0016) SOP Class UID                       UI: Secondary Capture Image Storage
(0008, 0018) SOP Instance UID                    UI: 1.2.826.0.1.3680043.2.1125.1.1916887417609428840454387466338522
(0008, 0020) Study Date                          DA: '20170629'
(0008, 0030) Study Time                          TM: '135711.801471'
(0008, 0050) Accession Number                    SH: ''
(0008, 0060) Modality                            CS: 'OT'
(0008, 0064) Conversion Type                     CS: 'WSD'
(0008, 0090) Referring Physician's Name          PN: ''
(0008, 103e) Series Description                  LO: 'Data Generated by Seg3D'
(0010, 0010) Patient's Name                      PN: ''
(0010, 0020) Patient ID                          LO: ''
(0010, 0030) Patient's Birth Date                DA: ''
(0010, 0040) Patient's Sex                       CS: ''
(0018, 0050) Slice Thickness                     DS: '2.5'
(0018, 0088) Spacing Between Slices              DS: '2.5'
(0018, 2010) Nominal Scanned Pixel Spacing       DS: ['0.62', '0.62']
(0020, 000d) Study Instance UID                  UI: 1.2.826.0.1.3680043.2.1125.1.46520048759963986552988627393739015
(0020, 000e) Series Instance UID                 UI: 1.2.826.0.1.3680043.2.1125.1.56150021888090725473257824116810052
(0020, 0010) Study ID                            SH: ''
(0020, 0011) Series Number                       IS: ''
(0020, 0013) Instance Number                     IS: ''
(0020, 0020) Patient Orientation                 CS: ''
(0020, 0032) Image Position (Patient)            DS: ['-164.7', '-154.65', '7.26']
(0028, 0002) Samples per Pixel                   US: 1
(0028, 0004) Photometric Interpretation          CS: 'MONOCHROME2'
(0028, 0010) Rows                                US: 460
(0028, 0011) Columns                             US: 576
(0028, 0100) Bits Allocated                      US: 32
(0028, 0101) Bits Stored                         US: 32
(0028, 0102) High Bit                            US: 31
(0028, 0103) Pixel Representation                US: 1
(0028, 1050) Window Center                       DS: '32767.5'
(0028, 1051) Window Width                        DS: '65535'
(0028, 1052) Rescale Intercept                   DS: '0'
(0028, 1053) Rescale Slope                       DS: '1'
(0028, 1054) Rescale Type                        LO: 'US'
(7fe0, 0010) Pixel Data                          OB or OW: Array of 1059840 bytes

It looks like the slice origin and spacing is correct in the files.

ITK-SNAP has the same problem as Seg3D's importer:

<img width="847" alt="itk-snap_image_summary" src="https://user-images.githubusercontent.com/1399377/27708115-0abf8496-5cd5-11e7-8d75-2ceca75c490a.png">

**Comment by aylakhan** [comment]
Also, Seg3D tries to compute spacing in the Z direction using the slice origins for the first and second slices in GDCMLayerImporter.cc. Since origin is set to [0,0,0] for all slices, Z spacing is 0 and Seg3D shows this error:

![seg3d_spacing_error](https://user-images.githubusercontent.com/1399377/27708793-301fea1c-5cd7-11e7-992e-d6772e2e38f2.png)

**Comment by jessdtate** [comment]
The slice thickness is read correctly, but it recalculates it based off the origin, which isn't read correctly.

**Comment by jessdtate** [comment]
This was not fixed in the latest ITK upgrade.  It will need some additional looking into.

**Comment by jessdtate** [comment]
This should be fixed in the ITK-4.23.0 branch and in the master branch.
