### ISSUE TITLE
implicit model tool crashing in windows 10.

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Seg3D#225]
When trying to run the implicit model tool in Windows 10 on a collaborator's machine, it crashed every time. Running release candidate 5.

**Comment by jessdtate** [comment]
This may be only a problem with windows 10 and the 3d convex hull option.  per @ajanson test.

**Comment by aylakhan** [comment]
It's possible - I didn't observe crashes on earlier Windows versions.

**Comment by dcwhite** [comment]
i'll need more specific replication steps

**Comment by ajanson** [comment]
## Steps to reproduce
Use Windows 10
Load in any volume data (it does not matter dicom or nrrd or type)
Click "Tools>Implicit Model"
Select "3D convex hull"
Select at least 3 points in a slice view
Click "Run FIlter"

Result: Seg3D crashes

**Comment by dcwhite** [comment]
thanks
