### ISSUE TITLE
Get Ubuntu package repository for Qt 5.9 packages

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#226]
A Ubuntu package repository is needed for Qt 5.9 packages for the Travis-CI build. Alternatively, see if Qt 5.9 packages are whitelisted and supported by Travis.

**Comment by allywarner** [comment]
Need to update github actions build with new Qt 5.12 requirement.

**Comment by allywarner** [comment]
Updated with #355 and #350
