### ISSUE TITLE
Import error Ubuntu

### ISSUE THREAD

**Issue by elitap** [SCIInstitute/Seg3D#229]
I got a odd import error when loading that file:

https://www.dropbox.com/s/ftdg4f6ktjkiz69/0522c0161.nrrd?dl=0

its a ct scan in .nrrd format. Somehow it just shows to have a Z dimension. Slicer and the OSx version loads the file just fine. The file is originally form the MICCAI (2015 i think) head and neck challenge dataset. 

I am on the recent version 2.4.0, build on an Ubuntu 17.04 using a prebuild Qt 5.9. I can also verify that bug #180 on my build.

![bildschirmfoto vom 2017-07-27 09-02-55](https://user-images.githubusercontent.com/9333139/28658344-1e73d596-72ab-11e7-8c4c-594741e5fea6.png)

**Comment by jessdtate** [comment]
@elitap do you have trouble loading in other nrrd files or formats, or just this one?

**Comment by elitap** [comment]
Thanks @jessdtate. No for now its just that file, so I first thought that it might be corrupt, but I loades smoothly in Slicer and on the osx version of seg3d 2.4. Other files I tested load without problems.

**Comment by elitap** [comment]
@jessdtate got another one with the spacing loaded incorrectly, this causes the label to be off when displayed over a volume.

Slicer loads it correctly see the screenshots:

![bildschirmfoto vom 2017-08-17 08-23-17](https://user-images.githubusercontent.com/9333139/29398669-310f4146-8326-11e7-86ce-d4a8676ce1ce.png)
![bildschirmfoto vom 2017-08-17 08-24-23](https://user-images.githubusercontent.com/9333139/29398670-31123a0e-8326-11e7-91a7-74ceb91eafdf.png)
![bildschirmfoto vom 2017-08-17 08-24-54](https://user-images.githubusercontent.com/9333139/29398668-310dc870-8326-11e7-81c7-ca84582f7c28.png)

The file I used:

[0522c0001_segmentation.nrrd.zip](https://github.com/SCIInstitute/Seg3D/files/1230297/0522c0001_segmentation.nrrd.zip)

Thank you. Still prefer seg3d over slicer, so it would be great if we could find out whats going wrong :-)

**Comment by jessdtate** [comment]
Here is the latest update from Karli:

1. When you open a project, import a series of data, then save and close, the import error with the nrrd is still happening
2. However, if you open project, import a series of data, save it as a nrrd, then save and close, it works fine when you reopen the project
3. You don't have to import the saved nrrd back in. it still works
4. But you can read in nrrd files that have been exported! Yayayayay!
Oh and it works if you do a project that won't load properly, load in more data and export it, then all a sudden it works for all the layers

**Comment by mildewey** [comment]
I cannot reproduce this on Ubuntu 16.04 either.
