### ISSUE TITLE
OS X 10.12 new project splash screen

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Seg3D#232]
Seg3D freezes when trying to create a new project in a location outside the default directory in 10.12.  I think this because the dialogue window appears behind the splash screen.  there may be a similar bug in the export segmentation dialogue

**Comment by allywarner** [comment]
Current behavior for OS X 10.11 (and earlier) and OS X 10.12 (with touch bar) is that the dialogue window is behind the splash screen. Current work around: Press F3 and click on Seg3D to get the window back.

**Comment by jessdtate** [comment]
We may need to check for other cases of this happening, similar to #277 .

**Comment by allywarner** [comment]
Fixed with pull request #285
