### ISSUE TITLE
new folder crashes in OSx 10.12

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Seg3D#233]
similar to scirun https://github.com/SCIInstitute/SCIRun/issues/1658

When trying to make a new folder in the file dialogue, software will crash.  Seems to be only in os x 10.12.

**Comment by allywarner** [comment]
Can only recreate on 10.12 with touch bar.

**Comment by jessdtate** [comment]
Process:               Seg3D2 [1339]
Path:                  /Users/USER/*/Seg3D2.app/Contents/MacOS/Seg3D2
Identifier:            Seg3D2
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [1337]
Responsible:           Seg3D2 [1339]
User ID:               501

Date/Time:             2018-07-19 10:11:03.539 -0600
OS Version:            Mac OS X 10.12.6 (16G1510)
Report Version:        12
Anonymous UUID:        220015BF-3AFA-BDBE-20F8-B7EED265C4B9


Time Awake Since Boot: 670 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0:
--> 
    __TEXT                 0000000102f7b000-00000001051d9000 [ 34.4M] r-x/rwx SM=COW  /Users/USER/*/Seg3D2.app/Contents/MacOS/Seg3D2

Application Specific Information:
Performing @selector(newFolder:) from sender NSButton 0x7f8f4463ca70

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_c.dylib             	0x00007fff8ea8eb52 strlen + 18
1   libsystem_c.dylib             	0x00007fff8eae992b strdup + 18
2   libxpc.dylib                  	0x00007fff8eca2b38 xpc_string_create + 11
3   libxpc.dylib                  	0x00007fff8eca2b0a xpc_dictionary_set_string + 24
4   com.apple.CharacterPicker     	0x00007fff83829771 -[CPKPreferences _loadRecentsAndFavoritesForDataSource:asDictionaryNotAsEntity:callAsync:usingBlock:] + 389
5   com.apple.CharacterPicker     	0x00007fff8382bf36 -[CPKPreferences recentsOfDataSourceSync:] + 156
6   com.apple.AppKit              	0x00007fff77333492 -[__NSEmojiDFREmojiListView _loadSystemRecents] + 71
7   com.apple.AppKit              	0x00007fff77331af1 -[__NSEmojiDFREmojiListView updateRecentsDisplay] + 61
8   com.apple.AppKit              	0x00007fff773313bf -[__NSEMIMDFRViewController initWithCloseActionTarget:selector:] + 1571
9   com.apple.AppKit              	0x00007fff778dee60 -[NSCharacterPickerTouchBarItem initWithIdentifier:] + 139
10  com.apple.AppKit              	0x00007fff778dedc0 +[NSCharacterPickerTouchBarItem characterPickerTouchBarItem] + 51
11  com.apple.AppKit              	0x00007fff7781c7f0 -[NSTouchBar itemForIdentifier:] + 507
12  com.apple.AppKit              	0x00007fff7781bfc8 -[NSTouchBar items] + 322
13  com.apple.AppKit              	0x00007fff772c3c03 -[NSTouchBarViewController _expandBars:] + 381
14  com.apple.AppKit              	0x00007fff772c43b8 -[NSTouchBarViewController _updateTree] + 126
15  com.apple.AppKit              	0x00007fff76e6d4eb -[NSView _doLayout] + 86
16  com.apple.AppKit              	0x00007fff76e6d098 -[NSView _layoutSubtreeWithOldSize:] + 497
17  com.apple.AppKit              	0x00007fff76e6d366 -[NSView _layoutSubtreeWithOldSize:] + 1215
18  com.apple.AppKit              	0x00007fff76e6d366 -[NSView _layoutSubtreeWithOldSize:] + 1215
19  com.apple.AppKit              	0x00007fff7764295b -[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 1516
20  com.apple.AppKit              	0x00007fff76e8b869 -[NSWindow(NSConstraintBasedLayout) _layoutViewTree] + 163
21  com.apple.AppKit              	0x00007fff76efac2e -[NSWindow(NSConstraintBasedLayout) layoutIfNeeded] + 269
22  com.apple.AppKit              	0x00007fff7766cb09 ___NSWindowGetDisplayCycleObserver_block_invoke.6222 + 67
23  com.apple.AppKit              	0x00007fff76f0c3b9 __37+[NSDisplayCycle currentDisplayCycle]_block_invoke + 454
24  com.apple.QuartzCore          	0x00007fff7edf5cc6 CA::Transaction::run_commit_handlers(CATransactionPhase) + 46
25  com.apple.QuartzCore          	0x00007fff7eeff8ac CA::Context::commit_transaction(CA::Transaction*) + 160
26  com.apple.QuartzCore          	0x00007fff7edf47a1 CA::Transaction::commit() + 475
27  com.apple.AppKit              	0x00007fff771ef8b1 __37+[NSDisplayCycle currentDisplayCycle]_block_invoke.31 + 323
28  com.apple.CoreFoundation      	0x00007fff792e5d37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
29  com.apple.CoreFoundation      	0x00007fff792e5ca7 __CFRunLoopDoObservers + 391
30  com.apple.CoreFoundation      	0x00007fff792c66d9 __CFRunLoopRun + 873
31  com.apple.CoreFoundation      	0x00007fff792c6114 CFRunLoopRunSpecific + 420
32  com.apple.HIToolbox           	0x00007fff78826ebc RunCurrentEventLoopInMode + 240
33  com.apple.HIToolbox           	0x00007fff78826bf9 ReceiveNextEventCommon + 184
34  com.apple.HIToolbox           	0x00007fff78826b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
35  com.apple.AppKit              	0x00007fff76dbda54 _DPSNextEvent + 1120
36  com.apple.AppKit              	0x00007fff775397ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
37  com.apple.AppKit              	0x00007fff770140b6 -[NSApplication _doModalLoop:peek:] + 497
38  com.apple.AppKit              	0x00007fff771f4374 __35-[NSApplication runModalForWindow:]_block_invoke + 64
39  com.apple.AppKit              	0x00007fff77011b98 -[NSApplication runModalForWindow:] + 137
40  com.apple.FinderKit           	0x00007fff85e71163 -[FI_NewFolderController runModalForSavePanel:] + 269
41  com.apple.FinderKit           	0x00007fff85e11cf4 -[FIFinderViewGutsController makeNewFolderForSavePanel:] + 127
42  com.apple.FinderKit           	0x00007fff85e16691 -[FIFinderView makeNewFolderForSavePanel:] + 43
43  libsystem_trace.dylib         	0x00007fff8ec8a3a7 _os_activity_initiate_impl + 53
44  com.apple.AppKit              	0x00007fff7753b721 -[NSApplication(NSResponder) sendAction:to:from:] + 456
45  com.apple.AppKit              	0x00007fff7701fcc4 -[NSControl sendAction:to:] + 86
46  com.apple.AppKit              	0x00007fff7701fbec __26-[NSCell _sendActionFrom:]_block_invoke + 136
47  libsystem_trace.dylib         	0x00007fff8ec8a3a7 _os_activity_initiate_impl + 53
48  com.apple.AppKit              	0x00007fff7701fb44 -[NSCell _sendActionFrom:] + 128
49  com.apple.AppKit              	0x00007fff77062539 -[NSButtonCell _sendActionFrom:] + 98
50  libsystem_trace.dylib         	0x00007fff8ec8a3a7 _os_activity_initiate_impl + 53
51  com.apple.AppKit              	0x00007fff7701e426 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2481
52  com.apple.AppKit              	0x00007fff77062272 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 798
53  com.apple.AppKit              	0x00007fff7701cddb -[NSControl mouseDown:] + 832
54  com.apple.AppKit              	0x00007fff776b724f -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 6341
55  com.apple.AppKit              	0x00007fff776b3a6c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 1942
56  com.apple.AppKit              	0x00007fff776b2f0a -[NSWindow(NSEventRouting) sendEvent:] + 541
57  com.apple.AppKit              	0x00007fff77537681 -[NSApplication(NSEvent) sendEvent:] + 1145
58  libqcocoa.dylib               	0x00000001098e4374 -[QNSApplication sendEvent:] + 84
59  com.apple.AppKit              	0x00007fff770140f8 -[NSApplication _doModalLoop:peek:] + 563
60  com.apple.AppKit              	0x00007fff771f5026 __33-[NSApplication runModalSession:]_block_invoke + 80
61  com.apple.AppKit              	0x00007fff771f4ef6 -[NSApplication runModalSession:] + 137
62  libqcocoa.dylib               	0x00000001098e0b2a QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 1930
63  org.qt-project.QtCore         	0x000000010680f561 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
64  org.qt-project.QtWidgets      	0x0000000105dba189 QDialog::exec() + 377
65  Seg3D2                        	0x000000010372134f Seg3D::Menu::new_project() + 623
66  org.qt-project.QtCore         	0x0000000106844151 QMetaObject::activate(QObject*, int, int, void**) + 913
67  org.qt-project.QtWidgets      	0x0000000105b61bff QAction::activate(QAction::ActionEvent) + 303
68  org.qt-project.QtCore         	0x0000000106844151 QMetaObject::activate(QObject*, int, int, void**) + 913
69  org.qt-project.QtCore         	0x000000010683d1dc QObject::event(QEvent*) + 156
70  org.qt-project.QtWidgets      	0x0000000105b6abfd QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
71  org.qt-project.QtWidgets      	0x0000000105b6d4cc QApplication::notify(QObject*, QEvent*) + 5852
72  org.qt-project.QtCore         	0x0000000106813814 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
73  org.qt-project.QtCore         	0x0000000106814470 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 560
74  libqcocoa.dylib               	0x00000001098e149e QCocoaEventDispatcherPrivate::processPostedEvents() + 190
75  libqcocoa.dylib               	0x00000001098e1d61 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 33
76  com.apple.CoreFoundation      	0x00007fff792e6321 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
77  com.apple.CoreFoundation      	0x00007fff792c721d __CFRunLoopDoSources0 + 557
78  com.apple.CoreFoundation      	0x00007fff792c6716 __CFRunLoopRun + 934
79  com.apple.CoreFoundation      	0x00007fff792c6114 CFRunLoopRunSpecific + 420
80  com.apple.HIToolbox           	0x00007fff78826ebc RunCurrentEventLoopInMode + 240
81  com.apple.HIToolbox           	0x00007fff78826bf9 ReceiveNextEventCommon + 184
82  com.apple.HIToolbox           	0x00007fff78826b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
83  com.apple.AppKit              	0x00007fff76dbda54 _DPSNextEvent + 1120
84  com.apple.AppKit              	0x00007fff775397ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
85  com.apple.AppKit              	0x00007fff76db23db -[NSApplication run] + 926
86  libqcocoa.dylib               	0x00000001098e0bff QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2143
87  org.qt-project.QtCore         	0x000000010680f561 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
88  org.qt-project.QtCore         	0x0000000106813e85 QCoreApplication::exec() + 341
89  Seg3D2                        	0x000000010365a0d8 QtUtils::QtApplication::exec() + 24
90  Seg3D2                        	0x0000000102f888fd Seg3D::Seg3DGui::run() + 285
91  Seg3D2                        	0x0000000102f7f03e main + 318
92  libdyld.dylib                 	0x00007fff8ea58235 start + 1

**Comment by allywarner** [comment]
Doesn't crash on 10.13 with touchbar.
