### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by AdamTTong** [SCIInstitute/Seg3D#234]
When I compile the source code with cmake 3.4 ,QT 5.9 and vs 2013 ,i encountered a problem
![image](https://user-images.githubusercontent.com/30587001/28765505-a8426fd0-75fd-11e7-9855-38a1a9fe75b7.png),can you give me some suggest? Thank you very much!
![image](https://user-images.githubusercontent.com/30587001/28765550-eabf11a6-75fd-11e7-8afc-f6354005969a.png)

**Comment by dcwhite** [comment]
User needs to install svn.
