### ISSUE TITLE
Output Measurement tool point one and point two

### ISSUE THREAD

**Issue by bzenger** [SCIInstitute/Seg3D#268]

**Comment by bzenger** [comment]
Is there a way to have the points (point 1 and point 2) from the measurment tool be exported as well as the length? This can be in a .txt or copy to clipboard function

**Comment by allywarner** [comment]
Made points copy and pastable.

**Comment by dcwhite** [comment]
Closed with https://github.com/SCIInstitute/Seg3D/pull/271
