### ISSUE TITLE
Exporting Sementation

### ISSUE THREAD

**Issue by wgood** [SCIInstitute/Seg3D#277]
Not necessarily the latest version of Seg3d. But, exporting a segmentation with the same name as an already existing file will ask if you want to overwrite the existing file, selecting either option results in the export failing.

**Comment by jessdtate** [comment]
There is an additional step after naming the file where the values of each mask are set.  Do you reach this window?

**Comment by wgood** [comment]
Yes. The process works exactly as expected. No new/missing windows. Just the file is not overwritten.

**Comment by wgood** [comment]
Jess showed me the error of my ways. The windows were grouping behind eachother. Related to #232
