### ISSUE TITLE
quick import failed to load the images

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/Seg3D#31]
Tried opening Seg3D an used the quick load with a set of MRI data in DICOM format (I had been able to do so with the previous version from Seg3D).

This time seg3d asked if I want to flip axis, as usual, and I just clicked next. Then It seemed to be loading to end up in the blank page from Seg3D.

Following that I went to File->Import Layer from Image Series and worked just fine.

**Comment by aylakhan** [comment]
Related to #29.

**Comment by aylakhan** [comment]
Splash screen quick open fixed in 12dce0b2ed40e820d5056def53a5ff6cc62907ab.
