### ISSUE TITLE
Windows 10 Seg3D 3.4.4 Binary STL writer issues

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/Seg3D#312]
Attempting to save an isosurface out with the binary stl writer does not write the file out properly as every program that attempts to read the file crashes (3D Slicer, Paraview, SCIRun, Meshlab).

1) Generate an isosurface from a mask layer
2) Export isosurface as binary stl
3) Attempt to read the file with the above programs

Result: Everything crashes
**Using vtk as the export option works properly
Attached is the same isosurface saved out as binary and ascii stl and an ascii vtk
The ascii stl file appears to be read in correctly by SCIRun and Slicer

[Seg3D_STLtest.zip](https://github.com/SCIInstitute/Seg3D/files/2862640/Seg3D_STLtest.zip)

**Comment by allywarner** [comment]
Do you get the same results in each software that you read the stl file into?
