### ISSUE TITLE
Cannot select layer in dilate-erode filter

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/Seg3D#32]
I load the dilate-erode filter to apply it on a mask that I had created.

Then I try to select a target layer in the first menu and there's no option in there (I actually have 2 layers open).

Seg3D does not allow me to run the filter when I select "Always use active layer".
Tried reopening the filter and it still has the same issue

**Comment by aylakhan** [comment]
Which dilate-erode filter, or was it both? Also, was the "select a mask layer to activate this filter" warning label visible in the filter GUI?

**Comment by jcollfont** [comment]
It was for both of them. 

Which warning do you mean?

**Comment by aylakhan** [comment]
There should be a red label at the bottom of the tool GUI if the wrong kind of layer is selected. Can you append a screen capture of Seg3D showing the problem?

**Comment by jcollfont** [comment]
I tried again and now seems to be fine... I don't know how to reproduce this issue

**Comment by aylakhan** [comment]
Ok, no worries. I'll close the issue for now. You can re-open if you see this problem again.
