### ISSUE TITLE
Slice/3d views shrink after export

### ISSUE THREAD

**Issue by karajohnson** [SCIInstitute/Seg3D#327]
I am testing the exporters on Seg3D 2.4.4 on MacOS Mojave 10.14.4. I exported a segmentation as a NRRD. When I interact with any of the slice views or 3D view after exporting, the viewing area shrinks to a small box in the bottom left-hand corner of the viewer. This does not occur if I'm interacting with the slices and have not exported anything. This seems to happen when exporting other file types too (NIFTI, compressed NIFTI, etc.).

**Comment by dcwhite** [comment]
@allywarner This is fixed on master now right?

**Comment by allywarner** [comment]
Yes!
