### ISSUE TITLE
Opened files revert to bottom left corner

### ISSUE THREAD

**Issue by etbloom** [SCIInstitute/Seg3D#338]
When I open a project into Seg3D 2.4.4 onto a Mac with Mojave 10.14.6, whenever I interact with it (clicking, hitting space bar), my view shrinks very small and moves to the bottom left corner. If I switch into/out of full screen view, it gets large again, but any interaction again reverts to the tiny aspect ratio. If I zoom, it will zoom but stay only in the tiny window. Is there a different version I should be using?

**Comment by dcwhite** [comment]
I believe this is fixed on the master branch. @allywarner can verify. We should have a new release coming out pretty soon with the fix.

**Comment by allywarner** [comment]
It is fixed in master!
