### ISSUE TITLE
Big Sur update compatibility.

### ISSUE THREAD

**Issue by Dahoody11** [SCIInstitute/Seg3D#389]
The application does not even open after I upgraded my Mac OS to Big Sur from Catalina.

**Comment by dcwhite** [comment]
What version of Seg3d? Sorry we don't have any Catalina test machines yet; one is coming soon. In general we don't support the absolute latest MacOS until it's been patched a few times (usually around 3-6 months), and we've had a chance to test our software on it. So we recommend not upgrading any machines that need to use our software until later.

**Comment by Dahoody11** [comment]
I'm using the latest one which you all updated in August (Seg3D v2.5.0). I made a mistake downloading the new Mac OS, hopefully a newer update can fix this issue. Thank you.

**Comment by dcwhite** [comment]
Building with newer Qt version fixed this one. We need to update the official installers.

**Comment by allywarner** [comment]
Fixed with newest build release 2.5.1
