### ISSUE TITLE
window volume view  : can't select target layer

### ISSUE THREAD

**Issue by gillescourtand** [SCIInstitute/Seg3D#399]
hi, 
I use version 2.5.0 for windows10 64.
I have two layers in the layer manager window but in the window volume view/volume rendering tab, there is no choice in the combobox "target layer" except "none"
so I can't apply any render modification.
would I have missed something?

**Comment by jessdtate** [comment]
What are the layer types?  The volume rendering function only works with data layers (as opposed to mask layers).  

If the layers are data layers, does this happen will all data, or just a subset?

**Comment by gillescourtand** [comment]
ok thank you I get it, it's not an issue, just a incompetent user !

**Comment by gillescourtand** [comment]
ok thank you I get it, I tried on mask, it's not an issue, just a incompetent user !
great software !
