### ISSUE TITLE
Scale mask values to 0-255

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#4]
From Sidnei Paciornik:

When I export a mask, the images are scaled between zero and one and the segmented regions are not immediately visible when I open the file in another program. Of course I can rescale the intensities in almost any IP program, but I think the images should be automatically scaled to 0-255 or, at least, allow this option. Migrated from GForge [issue tracker](https://gforge.sci.utah.edu/gf/project/seg3d2/tracker/?action=TrackerItemEdit&tracker_item_id=865&start=0).

**Comment by allywarner** [comment]
Using the export segmentation tool from the file menu, the user can set the mask layer values to be any integer.
