### ISSUE TITLE
Double Clicking a .nrrd File

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/Seg3D#41]
When I double click a .nrrd file to open it and pick to open it as a volume, Seg3D tries to open again and then will quit unexpectedly.

**Comment by aylakhan** [comment]
Behavior has changed; double clicking on a Nrrd file opens two instances of Seg3D on OS X. The NRRD gets loaded into the second instance.

**Comment by allywarner** [comment]
When NRRD is loaded the font on the import screen is black, but when a file is loaded through the find menu the font on the import screen is white.

**Comment by allywarner** [comment]
This does not crash anymore, but the first instance of Seg3D can be seen briefly before the import screen is shown.
