### ISSUE TITLE
python scripts in Seg3D 2.2

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Seg3D#47]
The new version of Seg3D (2.2) has changed a few things in the python interface, compared to Seg3D 2.1.5, which used python 3.2.  every function call (for Seg3D) returns a boolean, when many of them are supposed to return layer ids.  The padding.py and exportDistanceField.py function (emailed to Ayla) works in 2.1.5 but not in 2.2 because of this function (something with the time variable):

def wait_for_layer(layer):
#checks to make sure that the layer is available before trying operations on it.
  MAX_ITERATIONS=1000
  TIMEOUT=2
  c = threading.Condition()
  c.acquire()
  layerStatus = get(stateid=layer+"::data")
  counter = 1
  with c:
    while not layerStatus == "available":
      if counter > MAX_ITERATIONS:
        break
      counter += 1
      c.wait(TIMEOUT)
      layerStatus = get(stateid=layer+"::data")
      print('wainting for '+layer)

**Comment by aylakhan** [comment]
Python action context and PYTHONPATH settings fixed.
