### ISSUE TITLE
Importing nrrd file sometimes fails at using good origin and spacing.

### ISSUE THREAD

**Issue by P-EB** [SCIInstitute/Seg3D#78]
Cheers,

During IBBM, I noticed that my computer and a collegue's one were doing weird stuff when importing nrrd file.

The origin and the spacing weren't good.

Here is a screenshot of the segmentation before and after manual transformation.

We assumed it was connected to the locale of the computer (french, parsing of commas versus dots). LC_ALL is set to fr_FR.UTF-8.

We work on linux environment (Debian/Ubuntu respectively).

![seg3dbug](https://cloud.githubusercontent.com/assets/3770652/8660765/33844ac8-2970-11e5-810e-c898039dcbb5.png)

Available for complementary intel.

Thanks.

**Comment by aylakhan** [comment]
OS is Ubuntu 14.04 LTS.

**Comment by P-EB** [comment]
Actually, there were two OSes: Debian 8.1 (Jessie) and Ubuntu 14.04 LTS for Andjela.

**Comment by aylakhan** [comment]
Thank you for the clarification.

**Comment by aylakhan** [comment]
This has been confirmed to be a locale issue.

**Comment by allywarner** [comment]
Fixed by @mildewey.
