### ISSUE TITLE
Problem graphics hardware

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/Seg3D#81]
- Lenovo W520, NVIDIA Quadro 1000M/2000M: known to crash during program use, possible problem with threshold overlay shader (see #82)
- HP ProBook 6570b, Windows 7, Intel HD Graphics 4000: pixelated and non-uniformly shaded paintbrush edges
- Thinkpad, Intel HD 5500: 2 isosurfaces blend well (alpha=0.4, alpha=1), 3 (alpha=0.4, alpha=0.4, alpha=1) result in badly shaded triangles
- MacBook Air, 13 inch, mid-2012, OS X 10.9.5: distorted coronal plane rendering
- Lenovo laptop, Ubuntu 14.04 LTS with GeForce GTX 650M: bad isosurface transparency blending

**Comment by aylakhan** [comment]
MacBook Air, 13 inch, mid-2012, OS X 10.9.5:

![macbookair](https://cloud.githubusercontent.com/assets/1399377/8728471/86fea052-2ba2-11e5-9e5c-a41614b284dc.png)
![macbookair_screencap](https://cloud.githubusercontent.com/assets/1399377/8728473/891495a4-2ba2-11e5-955b-f9ac6f631af0.png)

**Comment by allywarner** [comment]
This seemed to be resolved on newer OS versions.
