### ISSUE TITLE
More efficient isosurfacing

### ISSUE THREAD

**Issue by TrystanMayfaire** [SCIInstitute/Seg3D#92]
When dealing with large segmentation volumes, such as those for serial EM, the resulting meshes can be overwhelmingly large using the current isosurface creation in Seg3D.  For example, routinely from my segmentation of EM, I end up with meshes that have >2 million faces.  Would it be possible to implement a more efficient process for isosurfacing to reduce the mesh size and--subsequently--the graphics and memory load for display?

**Comment by aylakhan** [comment]
See useful comments from Jess Tate in mailing list archives: https://lists.sci.utah.edu/sympa/arc/seg3d/2015-08/msg00008.html.
