### ISSUE TITLE
Ubuntu 14.4 resampling hang

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/Seg3D#93]
@aylakhan 

Original email:

"I'm having an issue with Seg3D 2.2.1 on Ubuntu 14.04 with the attached file. I need to shift the mask 1 pixel in x and y, and then resample it back into the original volume. Using transform works fine, but when I attempt to resample (by shift-clicking and dragging into the original object layer or using the resample tool) the resample gets to about 68% and then Seg3D immediately closes. Any thoughts or suggestions would be greatly appreciated."

Data: https://github.com/gduffley/randomFiles/blob/master/VCN_c07_input01.nrrd
Machine specs: https://github.com/gduffley/randomFiles/blob/master/hardinfo_report_PaulHolcomb.html

Places this operation does work:

1) When the data is cropped ahead of time (The data is a binary mask of mostly 0s)
2) Seg3D2.1.5 on opensuse13.2
3) Seg3D2.2.0 on OSx 10.10.4

**Comment by aylakhan** [comment]
Checking for failed resampling operations through the NRRD library should be more stable now. ITK-based resampling filters may also work better. Closed in 28770836a4e7bb7a1ef93db291a16a493611a9df.
